/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Formjava
 *
 * Created on Oct 24, 2012, 1:23:08 PM
 */
package com.darshan.desktop.alpha;

/**
 * @author Darshan Patel
 */
public class FormAlpha extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form FormAlpha */
	public FormAlpha() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panelImage1 = new PanelImage();
		panelAlpha1 = new PanelAlpha();
		panelImageAlpha1 = new PanelImageAlpha();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout panelImageAlpha1Layout = new javax.swing.GroupLayout(
				panelImageAlpha1);
		panelImageAlpha1.setLayout(panelImageAlpha1Layout);
		panelImageAlpha1Layout.setHorizontalGroup(panelImageAlpha1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 252, Short.MAX_VALUE));
		panelImageAlpha1Layout.setVerticalGroup(panelImageAlpha1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 253, Short.MAX_VALUE));

		javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(
				panelAlpha1);
		panelAlpha1.setLayout(panelAlpha1Layout);
		panelAlpha1Layout.setHorizontalGroup(panelAlpha1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						panelAlpha1Layout
								.createSequentialGroup()
								.addContainerGap(151, Short.MAX_VALUE)
								.addComponent(panelImageAlpha1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)));
		panelAlpha1Layout
				.setVerticalGroup(panelAlpha1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								panelAlpha1Layout
										.createSequentialGroup()
										.addContainerGap(47, Short.MAX_VALUE)
										.addComponent(
												panelImageAlpha1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(
				panelImage1);
		panelImage1.setLayout(panelImage1Layout);
		panelImage1Layout.setHorizontalGroup(panelImage1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(panelAlpha1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		panelImage1Layout.setVerticalGroup(panelImage1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(panelAlpha1,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new FormAlpha().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private PanelAlpha panelAlpha1;
	private PanelImage panelImage1;
	private PanelImageAlpha panelImageAlpha1;
	// End of variables declaration//GEN-END:variables
}
